### ISSUE TITLE
Changelog generation

### ISSUE THREAD

**Issue by jeaster12** [Cupcake-Design-System/Cupcake#2]
## Issue Type (bug, design, new component, etc)
Repository chore

## Description
As a developer I would like our changelogs and release notes to be automatic generated from a project's commit messages and metadata.

This could also entail an defining expected commit message guidelines

## URLs and/or external references
Conventional Changelog seems to be the most commonly used.
URLs: 
https://github.com/conventional-changelog/conventional-changelog
https://github.com/commitizen/cz-cli
https://github.com/marionebl/commitlint

## Tasks to complete:

- [ ]  Determine easiest and most efficient path.
- [ ]  Add needed dependencies to repo.
- [ ]  Begin document of usage and expectations in a contributing.md file in repo similar too - https://github.com/angular/angular/blob/master/CONTRIBUTING.md
